Fix: control chain code not being compiled in mod-host. Closes #50

diff --git a/build-modtools b/build-modtools
--- a/build-modtools
+++ b/build-modtools
@@ -1,9 +1,52 @@
 #!/bin/sh
-export WORKDIR=/home/andrea/Alabs/Devel/mod/
+SRC_ROOT=$(pwd)
+export WORKDIR=/home/andrea/Alab/Devel/mod/
+
+# setup the environment for the build
 source ../mod-plugin-builder/local.env moddwarf-new
+
+# build dependencies
+if [[ "$1" == "build-deps" ]]
+  then
+
+    # build the cc-master library
+    echo "Building cc-master library"
+    cd $SRC_ROOT/deps/cc-master
+    if pkg-config cc_client; then
+        echo "uninstalling cc-master"
+        ./waf uninstall || echo "Failed to uninstall cc-master, continuing with build";
+    fi
+    ./waf configure --prefix=$WORKDIR/moddwarf-new/host/usr/aarch64-buildroot-linux-gnu/sysroot/usr || { echo "Failed to configure cc-master"; exit 1; }
+    ./waf build || { echo "Failed to build cc-master"; exit 1; }
+    ./waf install || { echo "Failed to install cc-master"; exit 1; }
+    cd $SRC_ROOT
+
+    exit 0
+fi
+
+# check if the dependencies are installed
+echo -n
+if pkg-config --exists cc_client; then
+    echo "cc_client...: found"
+else
+    echo "cc_client...: not found (use build-deps parameter to rebuild and install cc-master)"
+    exit 1
+fi
+if pkg-config --exists hylia; then
+    echo "hylia.......: found"
+else
+    echo "hylia.......: not found"
+    exit 1
+fi
+
+echo -n
+# build the modtools library
 echo "Building modtools library" 
 make -C mod-ui/utils clean
 make -C mod-ui/utils
+
+# build mod-host
 echo "Building mod-host"
+# build mod-host
 make -C mod-host clean
 make -C mod-host
diff --git a/create-image b/create-image
--- a/create-image
+++ b/create-image
@@ -1,8 +1,8 @@
 #!/bin/bash
-if [ "$1" != "update" ] && [ "$1" != "build" ] && [ "$1" != "tag" ] && [ "$1" != "release" ]
+if [ "$1" != "update" ] && [ "$1" != "build" ] && [ "$1" != "build-deps" ] && [ "$1" != "tag" ] && [ "$1" != "release" ]
   then
 	echo "Invalid command supplied"
-	echo "    available commands: update | build | tag"
+	echo "    available commands: update | build | build-deps | tag"
 	exit 1
 fi
 
@@ -64,6 +64,23 @@ if [ "$1" = "tag" ]
 	git -C $SRC_DIR/mod-host tag -a $TAG_NAME -m "aLabs release $TAG_VERSION"
 	git tag -a $TAG_NAME -m "aLabs release $TAG_VERSION"
 	exit $?
+fi
+
+if [ "$1" = "build-deps" ]
+  then
+	echo 'Cloning dependencies'
+	if [ ! -d $SRC_DIR/deps/cc-master ]; then
+		git clone --depth 1 --branch master https://github.com/mod-audio/cc-master.git $SRC_DIR/deps/cc-master
+	fi
+
+	echo 'Building dependencies'
+	bash build-modtools build-deps
+	if [ ! $? -eq 0 ]; then
+		echo 'Fail to build dependencies'
+		exit 1
+	fi
+	echo 'Dependencies built successfully. Use create-image with build or release to build the image'
+	exit 0
 fi
 
 echo 'MOD IMAGE BUILDER'
